Numpy Implementation

In [4]:
import numpy as np

In [5]:
a = np.arange(12).reshape(3,4)

In [6]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [10]:
print(a.flatten())

#to combine two arrays, we can use vstack or hstack and then use .flatten() to get a singular final array

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [13]:
#we can do this as well to iterate through np arrays refer to more documentation on nditer for more info

for x in np.nditer(a,order="c"):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [14]:
for x in np.nditer(a,order="f"):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [22]:
# we can use flags to have a lot of functionality while iterating for ex:

#example1:

for x in np.nditer(a,order="f", flags=["external_loop"]):
    print(x)



[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [24]:
#example2:

for x in np.nditer(a, op_flags=["readwrite"]):
    x[...]=x*x

In [25]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [27]:
b = np.arange(3,15,4).reshape(3,1)

#we can also refer to a differnt array while iterating another array using:

b

array([[ 3],
       [ 7],
       [11]])

In [29]:
for x, y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
